# SPDX-License-Identifier: GPL-2.0-only
# Copyright (C) 2025-2026 IOWA-Tech - Giovanni Lorenzin
# Copyright (C) Torsten Seemann (upstream `mlst`, from which WMLST is ported)
"""Scoring, status and duplicate-code tests. docs/ARCHITECTURE.md 5.9, 5.15.

The centrepiece is :func:`test_all_986_tuples`, which asserts every row of
``tests/golden/scores.tsv`` -- a table generated by running the REAL Perl
``mlst`` arithmetic. 79 of its 986 rows disagree with exact-rational maths
because Perl uses IEEE-754 doubles, so a Decimal/Fraction implementation
fails here and nowhere else.

Runnable as ``python3 -m pytest tests/test_scoring.py`` or ``python3
tests/test_scoring.py``.
"""

from __future__ import annotations

import os
import sys
from fractions import Fraction

sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

from wmlst.engine import (
    classify,
    score_signature,
    sort_duplicate_codes,
    status_column,
)

HERE = os.path.dirname(os.path.abspath(__file__))
SCORES_TSV = os.path.join(HERE, "golden", "scores.tsv")


def _signature(nlocii: int, n_tilde: int, n_question: int, n_dash: int) -> str:
    """A signature carrying exactly the requested marker counts.

    The scoring function counts characters, so the filler codes must contain
    none of ``~``, ``?`` or ``-``.
    """
    n_plain = nlocii - n_tilde - n_question - n_dash
    assert n_plain >= 0
    fields = (["~1"] * n_tilde + ["1?"] * n_question + ["-"] * n_dash
              + ["1"] * n_plain)
    return "/".join(fields)


def _load_scores():
    rows = []
    with open(SCORES_TSV, encoding="utf-8", newline=None) as fh:
        header = fh.readline().split()
        assert header == ["nlocii", "n_tilde", "n_question", "n_dash",
                          "score"], header
        for line in fh:
            line = line.strip()
            if not line:
                continue
            nlocii, n_tilde, n_question, n_dash, score = (
                int(x) for x in line.split())
            rows.append((nlocii, n_tilde, n_question, n_dash, score))
    return rows


def test_scores_tsv_is_the_expected_table():
    """The golden table must be present and complete (986 tuples, 3..10 loci)."""
    rows = _load_scores()
    assert len(rows) == 986
    assert {r[0] for r in rows} == set(range(3, 11))


def test_all_986_tuples():
    """Section 5.9 step 43: every Perl-generated tuple, exactly.

    Acceptance-checklist item 3. The ``st`` argument is ``'-'`` because the
    reference table records the pre-``+10`` score.
    """
    failures = []
    for nlocii, n_tilde, n_question, n_dash, expected in _load_scores():
        sig = _signature(nlocii, n_tilde, n_question, n_dash)
        got = score_signature(sig, nlocii, "-")
        if got != expected:
            failures.append((nlocii, n_tilde, n_question, n_dash, expected, got))
    assert not failures, "%d of 986 tuples wrong, first: %r" % (
        len(failures), failures[:5])


def test_ieee754_really_is_required():
    """At least one golden row must disagree with exact-rational arithmetic.

    If this ever stops finding disagreements the golden table has been
    regenerated from something other than Perl, and the float mandate in
    section 5.9 step 43 has quietly lost its teeth.
    """
    divergent = 0
    for nlocii, n_tilde, n_question, n_dash, expected in _load_scores():
        exact = (Fraction(nlocii)
                 - Fraction(3, 10) * n_tilde
                 - Fraction(1, 2) * n_question
                 - Fraction(1) * n_dash) * 90 / nlocii
        if int(exact) != expected:
            divergent += 1
    assert divergent == 79, divergent


def test_multiplication_order_is_not_reassociable():
    """``int(s*90/n)`` != ``int(s*(90/n))`` for the pinned shapes (5.9 step 43)."""
    # n=7, three '~', one '?'
    sig = _signature(7, 3, 1, 0)
    assert score_signature(sig, 7, "-") == 71
    s = 7.0 - 0.3 * 3 - 0.5 * 1
    assert int(s * (90 / 7)) == 72          # the WRONG reassociation
    # n=9, one '~'
    assert score_signature(_signature(9, 1, 0, 0), 9, "-") == 86
    s = 9.0 - 0.3
    assert int(s * (90 / 9)) == 87          # the WRONG reassociation


def test_int_truncates_toward_zero_not_floor():
    """Section 5.9 step 43: ``//`` is wrong for a negative intermediate."""
    # A 7-locus scheme with 7 '?' and 4 '-' cannot happen, but the arithmetic
    # must still truncate: int(-0.5*90/7) == -6 while (-0.5*90/7)//1 == -7.0.
    value = -0.5 * 90 / 7
    assert int(value) == -6
    assert value // 1 == -7.0


def test_st_bonus_is_exactly_ten():
    assert score_signature(_signature(7, 0, 0, 0), 7, "-") == 90
    assert score_signature(_signature(7, 0, 0, 0), 7, "184") == 100


def test_seven_locus_reference_anchors():
    """The regression anchors quoted in section 5.9."""
    anchors = {
        (0, 0, 0): (90, 100),
        (1, 0, 0): (86, 96),
        (0, 1, 0): (83, 93),
        (0, 0, 1): (77, 87),
        (0, 0, 2): (64, 74),
        (0, 0, 3): (51, 61),
        (0, 0, 4): (38, 48),
    }
    for (t, q, d), (no_st, with_st) in anchors.items():
        sig = _signature(7, t, q, d)
        assert score_signature(sig, 7, "-") == no_st, (t, q, d)
        assert score_signature(sig, 7, "1") == with_st, (t, q, d)


def test_aphagocytophilum_can_never_reach_100():
    """Section 5.19a: 8 header genes, 7 .tfa files, so one field is always '-'."""
    sig = _signature(8, 0, 0, 1)
    assert score_signature(sig, 8, "-") == 78
    assert score_signature(sig, 8, "12") == 88


def test_halobacteria_and_mhominis_ceilings():
    """Section 5.19b: the uncallable loci cap these two schemes."""
    assert score_signature(_signature(5, 0, 0, 2), 5, "-") == 54
    assert score_signature(_signature(10, 0, 0, 1), 10, "-") == 81


# ---------------------------------------------------------------------------
# 5.15 step 51 -- the numeric duplicate sort
# ---------------------------------------------------------------------------
def test_duplicate_sort_pinned_case():
    """test.sh:123-126."""
    assert sort_duplicate_codes("10.001,2.002,2.001") == "2.001,2.002,10.001"


def test_duplicate_sort_needs_both_guards():
    """B5: only a comma-bearing, purely numeric field is reordered."""
    assert sort_duplicate_codes("~5,6") == "~5,6"
    assert sort_duplicate_codes("5?,6") == "5?,6"
    assert sort_duplicate_codes("6,5") == "5,6"
    assert sort_duplicate_codes("16") == "16"
    assert sort_duplicate_codes("-") == "-"
    assert sort_duplicate_codes("1,1") == "1,1"


def test_duplicate_sort_survives_a_malformed_field():
    """Unreachable with the shipped DB, but it must not raise."""
    assert sort_duplicate_codes("1,,2") == "1,,2"
    assert sort_duplicate_codes("1,2.3.4") == "1,2.3.4"


def test_duplicate_sort_is_stable():
    assert sort_duplicate_codes("2,1,2") == "1,2,2"


# ---------------------------------------------------------------------------
# 5.15 step 52 -- status_column
# ---------------------------------------------------------------------------
def test_status_order_is_the_specification():
    assert status_column("184", 100, ["16", "1"]) == "PERFECT"
    assert status_column("-", 0, []) == "NONE"
    assert status_column("-", 90, ["7", "1", "1"]) == "NOVEL"
    assert status_column("-", 90, ["7", "1,1"]) == "MIXED"
    assert status_column("-", 51, ["~66", "-"]) == "MISSING"
    assert status_column("-", 60, ["~66", "~1"]) == "BAD"
    assert status_column("-", 74, ["~66", "20"]) == "OK"


def test_perfect_wins_over_everything_even_with_null_codes():
    """A rewritten null still reports PERFECT (5.15, B3)."""
    assert status_column("64", 100, ["10", "0", "15"]) == "PERFECT"


def test_decimal_st_is_not_perfect():
    assert status_column("206.2", 100, ["1"]) != "PERFECT"


def test_missing_tests_containment_not_equality():
    """MISSING fires on a code that CONTAINS '-', not one that equals it."""
    assert status_column("-", 80, ["1-2"]) == "MISSING"


def test_none_beats_novel_when_score_is_zero():
    assert status_column("-", 0, ["1", "2"]) == "NONE"


# ---------------------------------------------------------------------------
# 3.2.1 -- classify
# ---------------------------------------------------------------------------
def test_classify_order():
    assert classify("-") == "missing"
    assert classify("0") == "null"
    assert classify("1,2") == "multiple"
    assert classify("~16") == "novel"
    assert classify("16?") == "partial"
    assert classify("16") == "exact"
    assert classify("2.002") == "exact"


def test_classify_null_is_tested_before_the_numeric_case():
    """'0' is the /- -> /0 rewrite, never an allele named zero (3.2.1)."""
    assert classify("0") == "null"
    assert classify("00") == "exact"


if __name__ == "__main__":
    failed = 0
    for name, fn in sorted(globals().items()):
        if name.startswith("test_") and callable(fn):
            try:
                fn()
                print("PASS %s" % name)
            except AssertionError as exc:
                failed += 1
                print("FAIL %s: %s" % (name, exc))
    print("%s" % ("ALL PASS" if not failed else "%d FAILED" % failed))
    sys.exit(1 if failed else 0)
