# -*- mode: python ; coding: utf-8 -*-
# SPDX-License-Identifier: GPL-2.0-only
# Copyright (C) 2025-2026 IOWA-Tech - Giovanni Lorenzin
# Copyright (C) Torsten Seemann (upstream `mlst`, from which WMLST is ported)
#
# PyInstaller spec for WMLST -- docs/ARCHITECTURE.md section 13.1.
#
#   pyinstaller --noconfirm --clean packaging/wmlst.spec
#
# Produces ONE folder, dist/WMLST/, containing TWO executables:
#
#   WMLST.exe       console=False   the GUI. Must never flash a console window.
#   wmlst-cli.exe   console=True    the command line, byte-compatible with mlst.
#
# Why one-folder and not one-file (this is not a preference):
#   a one-file build unpacks its whole payload into %TEMP% on every launch. The
#   payload here is 1,108 allele files plus a 74 MB BLAST index, so every start
#   would cost 20-60 s with Defender on, the bootstrapped blastn.exe would have
#   no stable path to live at, and the derived index would be rebuilt forever
#   because its directory evaporates at exit.
#
# Why MERGE is mandatory:
#   the two executables share the 116 MB database and the whole Python runtime.
#   Without MERGE, COLLECT writes both payloads and the folder doubles.

import os
import sys

from PyInstaller.building.api import COLLECT, EXE, MERGE, PYZ
from PyInstaller.building.build_main import Analysis
from PyInstaller.building.datastruct import Tree

# --------------------------------------------------------------------------
# Paths. SPECPATH is set by PyInstaller to the directory holding this file.
# --------------------------------------------------------------------------
PACKAGING = os.path.abspath(SPECPATH)                      # noqa: F821
REPO = os.path.dirname(PACKAGING)
BUILDAUX = os.path.join(PACKAGING, "build")
ICON = os.path.join(PACKAGING, "wmlst.ico")
VERSION_INFO = os.path.join(PACKAGING, "version_info.txt")
RUNTIME_HOOK = os.path.join(PACKAGING, "runtime_hook_noconsole.py")

# Optional pre-staged BLAST+ payload. The repository never contains binaries;
# the Windows release workflow drops blastn.exe, makeblastdb.exe, nghttp2.dll
# and the NCBI LICENSE / BLAST_PRIVACY notices in here before building, so the
# installer ships a tool that works offline on first run. When the directory is
# absent the application falls back to `wmlst --bootstrap-blast` at runtime.
BLAST_PAYLOAD = os.path.join(PACKAGING, "payload", "blast")

if not os.path.isfile(ICON):
    raise SystemExit(
        "packaging/wmlst.ico is missing. Run: python packaging/make_icon.py"
    )

os.makedirs(BUILDAUX, exist_ok=True)


def _write_entry(filename, module):
    """Emit a two-line launcher for one console.

    PyInstaller analyses a *script*, and WMLST's real entry points are
    ``[project.scripts]`` names rather than files on disk. Generating the
    launchers here keeps the exe list and pyproject.toml from drifting.

    ``multiprocessing.freeze_support()`` is the FIRST statement executed, as
    section 13.1 requires: without it, every worker process spawned by --jobs
    re-runs the GUI, and the user gets N copies of the main window.
    """
    path = os.path.join(BUILDAUX, filename)
    source = (
        "# SPDX-License-Identifier: GPL-2.0-only\n"
        "# Generated by packaging/wmlst.spec -- do not edit, do not commit.\n"
        "import multiprocessing\n"
        "import sys\n"
        "\n"
        "multiprocessing.freeze_support()\n"
        "\n"
        "from %s import main\n"
        "\n"
        "if __name__ == '__main__':\n"
        "    sys.exit(main())\n" % module
    )
    with open(path, "w", encoding="utf-8", newline="\n") as handle:
        handle.write(source)
    return path


ENTRY_GUI = _write_entry("entry_gui.py", "wmlst.gui")
ENTRY_CLI = _write_entry("entry_cli.py", "wmlst.cli")

# --------------------------------------------------------------------------
# Payload
# --------------------------------------------------------------------------
# The database ships as data, not as a package resource, so the frozen tree
# mirrors the source tree and WMLST_DBDIR points at the same relative layout in
# both. `blast` is excluded: it is a 180 MB derived index, rebuilt on the user's
# machine in ~12 s, and shipping it would triple the installer.
DB_TREE = Tree(
    os.path.join(REPO, "db"),
    prefix="db",
    excludes=["blast", "__pycache__", "*.pyc", "*.staging", ".backup"],
)

DATAS = [
    (os.path.join(REPO, "LICENSE"), "."),
    (os.path.join(REPO, "NOTICE"), "."),
    (os.path.join(REPO, "README.md"), "."),
    (os.path.join(REPO, "CITATION.cff"), "."),
]
DATAS = [(src, dst) for src, dst in DATAS if os.path.exists(src)]

if os.path.isdir(BLAST_PAYLOAD):
    for name in sorted(os.listdir(BLAST_PAYLOAD)):
        full = os.path.join(BLAST_PAYLOAD, name)
        if os.path.isfile(full):
            DATAS.append((full, "blast"))

# --------------------------------------------------------------------------
# Imports PyInstaller's static analysis cannot see
# --------------------------------------------------------------------------
HIDDEN = [
    # The package's own modules, several of which are reached only by name.
    "wmlst", "wmlst.any2fasta", "wmlst.blastbin", "wmlst.branding",
    "wmlst.cli", "wmlst.engine", "wmlst.gui", "wmlst.report",
    "wmlst.schemes", "wmlst.updatedb", "wmlst.version",
    # Tkinter submodules are imported lazily by tkinter itself.
    "tkinter", "tkinter.ttk", "tkinter.filedialog", "tkinter.messagebox",
    "tkinter.scrolledtext", "tkinter.font", "tkinter.simpledialog",
    "tkinter.colorchooser",
    # Decompression back-ends for the input fixtures (.gz, .bz2, .zip).
    "bz2", "gzip", "lzma", "zipfile", "zlib", "tarfile",
    # urllib needs these for the PubMLST/NCBI HTTPS fetches; on a slim system
    # image the encodings ones are the classic missing pair.
    "ssl", "http.client", "urllib.request", "urllib.error", "urllib.parse",
    "encodings.idna", "encodings.utf_8", "encodings.cp1252",
    # --jobs workers.
    "multiprocessing", "multiprocessing.pool", "multiprocessing.spawn",
    "concurrent.futures", "concurrent.futures.thread",
    # Miscellaneous late imports.
    "csv", "json", "hashlib", "webbrowser", "secrets", "uuid", "sqlite3",
]

# tkinterdnd2 is optional (MIT). Bundle it when the build machine has it, and
# say so; the application degrades to a Browse button when it is missing.
try:
    from PyInstaller.utils.hooks import collect_all as _collect_all

    _dnd_datas, _dnd_binaries, _dnd_hidden = _collect_all("tkinterdnd2")
except Exception:
    _dnd_datas, _dnd_binaries, _dnd_hidden = [], [], []
if _dnd_hidden:
    HIDDEN += list(_dnd_hidden)
    DATAS += list(_dnd_datas)
    print("wmlst.spec: bundling optional tkinterdnd2 (drag-and-drop enabled)")
else:
    print("wmlst.spec: tkinterdnd2 not installed; drag-and-drop will be disabled")

# --------------------------------------------------------------------------
# Exclusions -- section 13.1. PIL is on this list deliberately: the icon is
# generated by packaging/make_icon.py with zlib and struct, so nothing in the
# shipped application has any business importing Pillow.
# --------------------------------------------------------------------------
EXCLUDES = [
    "numpy", "scipy", "pandas", "matplotlib", "PIL", "Pillow",
    "pytest", "_pytest", "py", "nose", "hypothesis",
    "setuptools", "pkg_resources", "pip", "wheel", "distutils",
    "IPython", "jupyter", "notebook", "nbformat",
    "pydoc_data", "lib2to3", "idlelib", "turtledemo", "test", "tests",
    "curses", "readline",
]

BINARIES = list(_dnd_binaries)

_common = dict(
    pathex=[REPO],
    binaries=BINARIES,
    datas=DATAS,
    hiddenimports=HIDDEN,
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[RUNTIME_HOOK],
    excludes=EXCLUDES,
    noarchive=False,
    optimize=0,
)

gui_a = Analysis([ENTRY_GUI], **_common)
cli_a = Analysis([ENTRY_CLI], **_common)

# Share one copy of the runtime and the database between the two executables.
MERGE((gui_a, "WMLST", "WMLST"), (cli_a, "wmlst-cli", "wmlst-cli"))

gui_pyz = PYZ(gui_a.pure, gui_a.zipped_data)
cli_pyz = PYZ(cli_a.pure, cli_a.zipped_data)

_exe_common = dict(
    exclude_binaries=True,
    bootloader_ignore_signals=False,
    debug=False,
    strip=False,
    # UPX is OFF and stays off: it corrupts the MSVC runtime DLLs CPython ships
    # (VCRUNTIME140*.dll), and a packed exe is a well-known heuristic trigger
    # for exactly the AV false positives an unsigned build can least afford.
    upx=False,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
    icon=ICON,
)
if sys.platform == "win32" and os.path.isfile(VERSION_INFO):
    _exe_common["version"] = VERSION_INFO

gui_exe = EXE(
    gui_pyz,
    gui_a.scripts,
    [],
    name="WMLST",
    console=False,   # THE point of the two-exe split. Never change this.
    **_exe_common
)

cli_exe = EXE(
    cli_pyz,
    cli_a.scripts,
    [],
    name="wmlst-cli",
    console=True,
    **_exe_common
)

coll = COLLECT(
    gui_exe,
    gui_a.binaries,
    gui_a.datas,
    cli_exe,
    cli_a.binaries,
    cli_a.datas,
    DB_TREE,
    strip=False,
    upx=False,
    upx_exclude=[],
    name="WMLST",
)
