# -*- mode: python ; coding: utf-8 -*-
# SPDX-License-Identifier: GPL-2.0-only
# Copyright (C) 2025-2026 IOWA-Tech - Giovanni Lorenzin
# Copyright (C) Torsten Seemann (upstream `mlst`, from which WMLST is ported)
#
# PyInstaller spec for WMLST -- docs/ARCHITECTURE.md section 13.1.
#
#   pyinstaller --noconfirm --clean packaging/wmlst.spec
#
# Produces ONE folder, dist/WMLST/, containing TWO executables:
#
#   WMLST.exe       console=False   the GUI. Must never flash a console window.
#   wmlst-cli.exe   console=True    the command line, byte-compatible with mlst.
#
# Why one-folder and not one-file (this is not a preference):
#   a one-file build unpacks its whole payload into %TEMP% on every launch. The
#   payload here is 1,108 allele files plus a 74 MB BLAST index, so every start
#   would cost 20-60 s with Defender on, the bootstrapped blastn.exe would have
#   no stable path to live at, and the derived index would be rebuilt forever
#   because its directory evaporates at exit.
#
# Why MERGE is mandatory:
#   the two executables share the 116 MB database and the whole Python runtime.
#   Without MERGE, COLLECT writes both payloads and the folder doubles.

import os
import sys

from PyInstaller.building.api import COLLECT, EXE, MERGE, PYZ
from PyInstaller.building.build_main import Analysis
from PyInstaller.building.datastruct import Tree

# --------------------------------------------------------------------------
# Paths. SPECPATH is set by PyInstaller to the directory holding this file.
# --------------------------------------------------------------------------
PACKAGING = os.path.abspath(SPECPATH)                      # noqa: F821
REPO = os.path.dirname(PACKAGING)
BUILDAUX = os.path.join(PACKAGING, "build")
ICON = os.path.join(PACKAGING, "wmlst.ico")
VERSION_INFO = os.path.join(PACKAGING, "version_info.txt")
RUNTIME_HOOK = os.path.join(PACKAGING, "runtime_hook_noconsole.py")

# Optional pre-staged BLAST+ payload. The repository never contains binaries;
# the Windows release workflow drops blastn.exe, makeblastdb.exe, nghttp2.dll
# and the NCBI LICENSE / BLAST_PRIVACY notices in here before building, so the
# installer ships a tool that works offline on first run. When the directory is
# absent the application falls back to `wmlst --bootstrap-blast` at runtime.
BLAST_PAYLOAD = os.path.join(PACKAGING, "payload", "blast")

if not os.path.isfile(ICON):
    raise SystemExit(
        "packaging/wmlst.ico is missing. Run: python packaging/make_icon.py"
    )

os.makedirs(BUILDAUX, exist_ok=True)


def _write_entry(filename, module):
    """Emit a two-line launcher for one console.

    PyInstaller analyses a *script*, and WMLST's real entry points are
    ``[project.scripts]`` names rather than files on disk. Generating the
    launchers here keeps the exe list and pyproject.toml from drifting.

    ``multiprocessing.freeze_support()`` is the FIRST statement executed, as
    section 13.1 requires: without it, every worker process spawned by --jobs
    re-runs the GUI, and the user gets N copies of the main window.
    """
    path = os.path.join(BUILDAUX, filename)
    source = (
        "# SPDX-License-Identifier: GPL-2.0-only\n"
        "# Generated by packaging/wmlst.spec -- do not edit, do not commit.\n"
        "import multiprocessing\n"
        "import sys\n"
        "\n"
        "multiprocessing.freeze_support()\n"
        "\n"
        "from %s import main\n"
        "\n"
        "if __name__ == '__main__':\n"
        "    sys.exit(main())\n" % module
    )
    with open(path, "w", encoding="utf-8", newline="\n") as handle:
        handle.write(source)
    return path


ENTRY_GUI = _write_entry("entry_gui.py", "wmlst.gui")
ENTRY_CLI = _write_entry("entry_cli.py", "wmlst.cli")

# --------------------------------------------------------------------------
# Payload
# --------------------------------------------------------------------------
# The database ships as data, not as a package resource, so the frozen tree
# mirrors the source tree and WMLST_DBDIR points at the same relative layout in
# both. `blast` is excluded: it is a 180 MB derived index, rebuilt on the user's
# machine in ~12 s, and shipping it would triple the installer.
DB_TREE = Tree(
    os.path.join(REPO, "db"),
    prefix="db",
    excludes=["blast", "__pycache__", "*.pyc", "*.staging", ".backup"],
)

DATAS = [
    (os.path.join(REPO, "LICENSE"), "."),
    (os.path.join(REPO, "NOTICE"), "."),
    (os.path.join(REPO, "README.md"), "."),
    (os.path.join(REPO, "CITATION.cff"), "."),
]
DATAS = [(src, dst) for src, dst in DATAS if os.path.exists(src)]

if os.path.isdir(BLAST_PAYLOAD):
    for name in sorted(os.listdir(BLAST_PAYLOAD)):
        full = os.path.join(BLAST_PAYLOAD, name)
        if os.path.isfile(full):
            DATAS.append((full, "blast"))

# --------------------------------------------------------------------------
# Imports PyInstaller's static analysis cannot see
# --------------------------------------------------------------------------
HIDDEN = [
    # The package's own modules, several of which are reached only by name.
    "wmlst", "wmlst.any2fasta", "wmlst.blastbin", "wmlst.branding",
    "wmlst.cli", "wmlst.engine", "wmlst.gui", "wmlst.perf", "wmlst.report",
    "wmlst.schemerefs", "wmlst.schemes", "wmlst.updatedb", "wmlst.version",
    # Tkinter submodules are imported lazily by tkinter itself.
    "tkinter", "tkinter.ttk", "tkinter.filedialog", "tkinter.messagebox",
    "tkinter.scrolledtext", "tkinter.font", "tkinter.simpledialog",
    "tkinter.colorchooser",
    # Decompression back-ends for the input fixtures (.gz, .bz2, .zip).
    "bz2", "gzip", "lzma", "zipfile", "zlib", "tarfile",
    # urllib needs these for the PubMLST/NCBI HTTPS fetches; on a slim system
    # image the encodings ones are the classic missing pair.
    "ssl", "http.client", "urllib.request", "urllib.error", "urllib.parse",
    "encodings.idna", "encodings.utf_8", "encodings.cp1252",
    # --jobs workers.
    "multiprocessing", "multiprocessing.pool", "multiprocessing.spawn",
    "concurrent.futures", "concurrent.futures.thread",
    # Miscellaneous late imports.
    "csv", "json", "hashlib", "webbrowser", "secrets", "uuid", "sqlite3",
]

# --------------------------------------------------------------------------
# tkinterdnd2 -- optional at RUNTIME, mandatory in a RELEASE BUILD
# --------------------------------------------------------------------------
# wmlst/gui.py imports tkinterdnd2 inside a try/except and degrades to the
# Browse button when it is absent (ARCHITECTURE.md C21). That degradation is
# correct for a `pip install wmlst` with no extras. It is NOT acceptable in a
# frozen release: dropping a FASTA on the window is the primary interaction of
# this product, and a build that silently lost it is indistinguishable from a
# good one until a user complains.
#
# So the spec refuses to build without it. `pip install -e ".[gui]"` (what both
# .github/workflows/ci.yml and release.yml already do) is the fix. A deliberate
# no-drag-and-drop build is still possible with WMLST_ALLOW_NO_DND=1.
#
# What "collected" has to mean here: tkinterdnd2 is a thin Python shim over the
# tkdnd Tcl extension, which lives in <package>/tkdnd/<platform>/ and is loaded
# by TkinterDnD._require() via os.path.dirname(__file__). Collecting the two
# Python modules and forgetting the Tcl/DLL payload produces an import that
# succeeds and a `package require tkdnd` that fails at window-creation time, so
# the presence of a tkdnd platform directory is checked explicitly.
ALLOW_NO_DND = os.environ.get("WMLST_ALLOW_NO_DND", "").strip().lower() in (
    "1", "true", "yes", "on",
)

#: Directory names TkinterDnD._require() may pick for a 64-bit Windows host.
DND_WIN_PLATFORMS = ("win-x64", "win-x64-tcl9")

_dnd_datas, _dnd_binaries, _dnd_hidden = [], [], []
_dnd_problem = ""

try:
    from PyInstaller.utils.hooks import collect_all as _collect_all
except ImportError as exc:                                   # pragma: no cover
    _dnd_problem = "PyInstaller.utils.hooks.collect_all is unavailable: %s" % exc
else:
    try:
        _dnd_datas, _dnd_binaries, _dnd_hidden = _collect_all("tkinterdnd2")
    except Exception as exc:
        _dnd_datas, _dnd_binaries, _dnd_hidden = [], [], []
        _dnd_problem = "collect_all('tkinterdnd2') failed: %s: %s" % (
            type(exc).__name__, exc,
        )

if not _dnd_problem and not _dnd_hidden:
    _dnd_problem = "tkinterdnd2 is not importable on the build interpreter"

if not _dnd_problem:
    # Every collected destination directory, e.g. 'tkinterdnd2/tkdnd/win-x64'.
    _dnd_dests = {
        str(dest).replace("\\", "/")
        for _src, dest in list(_dnd_datas) + list(_dnd_binaries)
    }
    _dnd_tkdnd = {d for d in _dnd_dests if "/tkdnd/" in d + "/"}
    if not _dnd_tkdnd:
        _dnd_problem = (
            "tkinterdnd2 was found but its bundled tkdnd Tcl extension was not "
            "collected; the frozen GUI would import tkinterdnd2 and then fail on "
            "`package require tkdnd`"
        )
    elif sys.platform == "win32" and not any(
        d.endswith(p) for d in _dnd_tkdnd for p in DND_WIN_PLATFORMS
    ):
        _dnd_problem = (
            "tkinterdnd2 ships no %s build of tkdnd; collected platforms: %s"
            % (" / ".join(DND_WIN_PLATFORMS), ", ".join(sorted(_dnd_tkdnd)))
        )

if _dnd_problem:
    _dnd_datas, _dnd_binaries, _dnd_hidden = [], [], []
    _message = (
        "\n"
        "wmlst.spec: drag-and-drop dependency is missing.\n"
        "  %s\n"
        "\n"
        "  Dropping a FASTA on the window is the primary interaction of WMLST,\n"
        "  and wmlst/gui.py degrades SILENTLY when tkinterdnd2 is absent, so a\n"
        "  build without it looks identical to a good one.\n"
        "\n"
        "  Fix it with:   python -m pip install -e \".[gui]\"\n"
        "           or:   python -m pip install \"tkinterdnd2>=0.3.0\"\n"
        "\n"
        "  To build deliberately without drag-and-drop, set WMLST_ALLOW_NO_DND=1.\n"
    ) % _dnd_problem
    if not ALLOW_NO_DND:
        raise SystemExit(_message)
    print(_message)
    print("wmlst.spec: WMLST_ALLOW_NO_DND is set; continuing without drag-and-drop")
else:
    HIDDEN += list(_dnd_hidden)
    DATAS += list(_dnd_datas)
    print(
        "wmlst.spec: bundling tkinterdnd2 (drag-and-drop enabled) -- "
        "%d data files, %d binaries, tkdnd platforms: %s"
        % (
            len(_dnd_datas),
            len(_dnd_binaries),
            ", ".join(sorted(d.rsplit("/", 1)[-1] for d in _dnd_tkdnd)),
        )
    )

# --------------------------------------------------------------------------
# Exclusions -- section 13.1. PIL is on this list deliberately: the icon is
# generated by packaging/make_icon.py with zlib and struct, so nothing in the
# shipped application has any business importing Pillow.
# --------------------------------------------------------------------------
EXCLUDES = [
    "numpy", "scipy", "pandas", "matplotlib", "PIL", "Pillow",
    "pytest", "_pytest", "py", "nose", "hypothesis",
    "setuptools", "pkg_resources", "pip", "wheel", "distutils",
    "IPython", "jupyter", "notebook", "nbformat",
    "pydoc_data", "lib2to3", "idlelib", "turtledemo", "test", "tests",
    "curses", "readline",
]

BINARIES = list(_dnd_binaries)

_common = dict(
    pathex=[REPO],
    binaries=BINARIES,
    datas=DATAS,
    hiddenimports=HIDDEN,
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[RUNTIME_HOOK],
    excludes=EXCLUDES,
    noarchive=False,
    optimize=0,
)

gui_a = Analysis([ENTRY_GUI], **_common)
cli_a = Analysis([ENTRY_CLI], **_common)

# Share one copy of the runtime and the database between the two executables.
MERGE((gui_a, "WMLST", "WMLST"), (cli_a, "wmlst-cli", "wmlst-cli"))

gui_pyz = PYZ(gui_a.pure, gui_a.zipped_data)
cli_pyz = PYZ(cli_a.pure, cli_a.zipped_data)

_exe_common = dict(
    exclude_binaries=True,
    bootloader_ignore_signals=False,
    debug=False,
    strip=False,
    # UPX is OFF and stays off: it corrupts the MSVC runtime DLLs CPython ships
    # (VCRUNTIME140*.dll), and a packed exe is a well-known heuristic trigger
    # for exactly the AV false positives an unsigned build can least afford.
    upx=False,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
    # NOTE: `icon` is deliberately NOT set here. It is passed per-executable
    # below, because the two executables must NOT look alike -- see the comment
    # on cli_exe.
)
if sys.platform == "win32" and os.path.isfile(VERSION_INFO):
    _exe_common["version"] = VERSION_INFO

gui_exe = EXE(
    gui_pyz,
    gui_a.scripts,
    [],
    name="WMLST",
    console=False,   # THE point of the two-exe split. Never change this.
    # The branded icon belongs to the windowed application and to nothing else.
    # WMLST.exe is the only file a user is ever invited to double-click.
    icon=ICON,
    **_exe_common
)

cli_exe = EXE(
    cli_pyz,
    cli_a.scripts,
    [],
    name="wmlst-cli",
    console=True,
    # NO custom icon, on purpose. Two files in one folder carrying the same
    # artwork, one of which opens a black console window and exits, is a trap:
    # the novice double-clicks whichever one Explorer happens to sort first and
    # concludes the program is broken. wmlst-cli.exe keeps the default console
    # icon so it reads as what it is -- a terminal tool -- and is reached by
    # typing its name, not by clicking it. Do not "restore" this to ICON.
    icon=None,
    **_exe_common
)

coll = COLLECT(
    gui_exe,
    gui_a.binaries,
    gui_a.datas,
    cli_exe,
    cli_a.binaries,
    cli_a.datas,
    DB_TREE,
    strip=False,
    upx=False,
    upx_exclude=[],
    name="WMLST",
)
